swagger: '2.0'
info:
  description: ''
  version: '2'
  title: CS_CONECTION
host: 'localhost:1150'
tags:
  - name: Account 
schemes:
  - http
paths:
  /login:
    put:
      tags:
        - Account
      summary: เช็คชื่อเข้าร่วมงาน
      consumes:
        - application/x-www-form-urlencoded
      produces:
        - application/json
      parameters:
        - name: id
          in: formData
          description: รหัสนักศึกษา
          required: true
          type: string
          default: '61050150'
        - name: password
          in: formData
          description: รหัสผ่านประจำตัว
          required: true
          type: string
          default: '1111'
      responses:
        '200':
          description: Update
          schema:
            $ref: '#/definitions/transaction200'
        '400':
          description: Bad Request
          schema:
            $ref: '#/definitions/badRequest400'
        '500':
          description: Internal Server Error
          schema:
            $ref: '#/definitions/transaction500'
  /getTotal:
    get:
      tags:
        - Account
      summary: เช็คยอดนักศึกษาที่เข้าร่วมงาน
      consumes:
        - application/x-www-form-urlencoded
      produces:
        - application/json
      responses:
        '200':
          description: GET
          schema:
            $ref: '#/definitions/transaction200'
        '400':
          description: Bad Request
          schema:
            $ref: '#/definitions/badRequest400'
        '500':
          description: Internal Server Error
          schema:
            $ref: '#/definitions/transaction500'
definitions:
  badRequest400:
    type: object
    properties:
      statusCode:
        type: number
        example: 400
      message:
        type: string
        example: <function_name> id is required
  transaction200:
    type: object
    properties:
      statusCode:
        type: number
        example: 200
      message:
        type: string
        example: 'Check in complete!!!'
  transaction500:
    type: object
    properties:
      statusCode:
        type: number
        example: 500
      message:
        type: string
        example: 'Internal Server Error'