swagger: '2.0'
info:
  description: ''
  version: '2'
  title: MVC_TEST
host: 'localhost:1150'
tags:
  - name: ATM
schemes:
  - http
paths:
  /deposit:
    post:
      tags:
        - ATM
      summary: ฝากเงิน
      consumes:
        - application/x-www-form-urlencoded
      produces:
        - application/json
      parameters:
        - name: account_id
          in: formData
          description: เลขบัญชี
          required: true
          type: string
          default: '2562342110001'
        - name: pin
          in: formData
          description: รหัสบัญชี
          required: true
          type: string
          default: '6969'
        - name: money
          in: formData
          description: จำนวนเงิน
          required: true
          type: integer
          default: 1000
      responses:
        '200':
          description: Update
          schema:
            $ref: '#/definitions/transaction200'
        '400':
          description: Bad Request
          schema:
            $ref: '#/definitions/badRequest400'
        '500':
          description: Internal Server Error
          schema:
            $ref: '#/definitions/transaction500'
  /withdraw:
    post:
      tags:
        - ATM
      summary: ถอนเงิน
      consumes:
        - application/x-www-form-urlencoded
      produces:
        - application/json
      parameters:
        - name: account_id
          in: formData
          description: เลขบัญชี
          required: true
          type: string
          default: '2562342110001'
        - name: pin
          in: formData
          description: รหัสบัญชี
          required: true
          type: string
          default: '6969'
        - name: money
          in: formData
          description: จำนวนเงิน
          required: true
          type: integer
          default: 1000
      responses:
        '200':
          description: Update
          schema:
            $ref: '#/definitions/transaction200'
        '400':
          description: Bad Request
          schema:
            $ref: '#/definitions/badRequest400'
        '500':
          description: Internal Server Error
          schema:
            $ref: '#/definitions/transaction500'
  /transfer:
    post:
      tags:
        - ATM
      summary: โอนเงิน
      consumes:
        - application/x-www-form-urlencoded
      produces:
        - application/json
      parameters:
        - name: account_id
          in: formData
          description: เลขบัญชี
          required: true
          type: string
          default: '2562342110001'
        - name: pin
          in: formData
          description: รหัสบัญชี
          required: true
          type: string
          default: '6969'
        - name: receive_account
          in: formData
          description: เลขบัญชีผู้รับ
          required: true
          type: string
          default: '2562342110002'
        - name: money
          in: formData
          description: จำนวนเงิน
          required: true
          type: integer
          default: 1000
      responses:
        '200':
          description: Update
          schema:
            $ref: '#/definitions/transaction200'
        '400':
          description: Bad Request
          schema:
            $ref: '#/definitions/badRequest400'
        '500':
          description: Internal Server Error
          schema:
            $ref: '#/definitions/transaction500'
  /checkBalance:
    post:
      tags:
        - ATM
      summary: Create student info
      description: Create Student info To DataBase
      consumes:
        - application/x-www-form-urlencoded
      produces:
        - application/json
      parameters:
        - name: account_id
          in: formData
          description: เลขบัญชี
          required: true
          type: string
          default: '2562342110001'
        - name: pin
          in: formData
          description: รหัสบัญชี
          required: true
          type: string
          default: '6969'
      responses:
        '200':
          description: Update
          schema:
            $ref: '#/definitions/transaction200'
        '400':
          description: Bad Request
          schema:
            $ref: '#/definitions/badRequest400'
        '500':
          description: Internal Server Error
          schema:
            $ref: '#/definitions/transaction500'
definitions:
  badRequest400:
    type: object
    properties:
      statusCode:
        type: number
        example: 400
      message:
        type: string
        example: <function_name> account_id is required
  transaction200:
    type: object
    properties:
      statusCode:
        type: number
        example: 200
      message:
        type: string
        example: 'Transaction has been submitted'
  transaction500:
    type: object
    properties:
      statusCode:
        type: number
        example: 500
      message:
        type: string
        example: 'Internal Server Error'
      
